### ISSUE TITLE
how can I rebuild the 201702: initial release?

### ISSUE THREAD

**Issue by ghost** [foss-xtensa/xtensa-config#1]
Hello, in my project I need to download the release version 201702: initial of the xtensa-config. However, I can't download from the server. Could you tell me how can I rebuild it? 
Thanks!

**Comment by jcmvbkbc** [comment]
I'm not sure what exactly you want to rebuild. There's only one source file in this repository: make-overlay.sh, you can't rebuild it. The 201702 release has an archive attached to it: sample_controller_linux.tgz, it's built by the Xtensa Processor Generator (XPG), you need to have XPG access to rebuild it (but if you have XPG access you can just download it from the XPG, it's a standard configuration).
